name = "memory-reflector"
type = "javascript"

account_id = "your-cloudflare-id"
workers_dev = true
compatibility_date = "2024-07-01"

[vars]
NOTION_API_KEY = ""
OPENAI_API_KEY = ""
NOTION_DB_ID = ""
